### ISSUE TITLE
FCD is trying to read invalid proposal from API.

### ISSUE THREAD

**Issue by jjangg96** [terra-project/fcd#109]
```
0|collector  | 04-27 13:20 [ERROR]: 500 - {"error":"internal"} /gov/proposals/16
0|collector  | APIError: 500 - {"error":"internal"} /gov/proposals/16
0|collector  |     at /root/fcd/src/lib/lcd.ts:38:11
0|collector  |     at tryCatcher (/root/fcd/node_modules/bluebird/js/release/util.js:16:23)
0|collector  |     at Promise._settlePromiseFromHandler (/root/fcd/node_modules/bluebird/js/release/promise.js:547:31)
0|collector  |     at Promise._settlePromise (/root/fcd/node_modules/bluebird/js/release/promise.js:604:18)
0|collector  |     at Promise._settlePromise0 (/root/fcd/node_modules/bluebird/js/release/promise.js:649:10)
0|collector  |     at Promise._settlePromises (/root/fcd/node_modules/bluebird/js/release/promise.js:725:18)
0|collector  |     at _drainQueueStep (/root/fcd/node_modules/bluebird/js/release/async.js:93:12)
0|collector  |     at _drainQueue (/root/fcd/node_modules/bluebird/js/release/async.js:86:9)
0|collector  |     at Async._drainQueues (/root/fcd/node_modules/bluebird/js/release/async.js:102:5)
0|collector  |     at Immediate.Async.drainQueues [as _onImmediate] (/root/fcd/node_modules/bluebird/js/release/async.js:15:14)
0|collector  |     at processImmediate (internal/timers.js:461:21)
```
Seems proposals 16 does not exist.
By this error can't save block #240341

**Comment by jjangg96** [comment]
Seems fixed
